config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :equipment_set_templates
resources :equipment_templates
resources :equipment_sets
resources :equipment_units

get 'equipment_set_templates/:id/upload', to: 'equipment_set_templates#show_upload'
post 'equipment_set_templates/:id/upload', to: 'equipment_set_templates#upload'

get 'equipment_set_templates/:id/error_inv_exel', to: 'equipment_set_templates#error_inv_exel'

get 'equipments/:id/edit_set', to: 'equipments#edit_set'

get 'multiply_issue/:id', :to => 'co#multiply'



# Роуты к шаблонам описывать тут

get 'report_co3/:year/:num', to: 'excel#make_co3'

get 'templates/report_co3/:type/:year/:num', to: 'templates#report_co3'
get 'projects/:project/co6/:num', to: 'templates#make_act_co6'

get 'repairs/list_svod', to: 'repairs#list_svod'
 get 'projects/:project/make_formular', to: 'formulars#make_formular'
get 'projects/:project/make_pasport', to: 'pasports#make_pasport'
get 'make_requisition/:id', :to => 'requisitions#make_requisition'
get 'technique_report/:id', :to => 'technique_report#technique_report'

#resources :organizations

resources :issues do
  member do
    get 'repairs/:file', to: 'repairs#make_file'
    get 'cartridges/:file', to: 'templates#make_file_for_cartridges'
    get 'receive_cartridges', to: 'cartridges#receive_to_tank'
  end
end

resources :projects do
  member do
    get 'act_co3/:year/:month', to: 'templates#make_act_co3'
    #get 'projects/act_co3/:project/:mon/:file', to: 'templates#make_act_co3'
  end
  # resources :printers
  resources :cartridges do
    collection do
      get 'new_tanker'
    end
  end

  resources :equipments do
    member do
      get 'select'
      get 'new_repair'
    end
  end
end

#get 'delete_repair/:equipment_request_id'
#get 'equipments/import' , :to => 'equipments#import'



# get 'projects/:project_id/printers' , :to => 'printers#index'
# get 'printers/:project_id/context_menu' , :to => 'printers#context_menu'
#
# post 'printers/:project/cartridge' , :to => 'printers#cartridge'
# get 'printers/import', :to => 'printers#import'
# get 'printers/export', :to => 'printers#export'
# get 'printers/upload', :to => 'printers#upload'

# get  'issues/:id/cartridge_category/:cartridge', :to => 'cartridges#edit'
# post 'issues/:id/cartridge_category/:cartridge', :to => 'cartridges#update'

post 'role_trackers/reload', :to => 'role_trackers#reload'
resources :role_trackers

resources :organizations do
  member do
    get 'add_cartridge'
    get 'remove_cartridge'
    get :context_menu
  end
  collection do
    get 'import'
    get 'synchronize'
  end
end
resources :floors do
  resources :places
  resources :rooms do
    collection do
      get 'quick_new'
      post 'quick_create'
    end
  end
  member do
    get 'plan'
  end

end
resources :places
#get 'organizations/import', :to => 'organizations#import'

resources :cartridge_categories
resources :printer_categories
resources :equipment_category_groups
resources :equipments
get 'equipments/delete_repair/:id/:project_id/:service_request_id' , :to => 'equipments#delete_repair'
get 'equipment/:equipment/link_to_issue/:issue', :to => 'equipments#set_link_to_issue'
#get 'equipment/destroy_link_from_issue/:issue', :to => 'equipments#destroy_link_from_issue'
get 'issues_without_link', :to => 'equipments#issues_without_link'
get 'synchronize', to: 'repairs#synchronize'

app/models/equipment_unit.rb
class EquipmentUnit < CiaDatabase
  self.table_name = "EQUIPMENTCOMPLECTUNITS"
  self.primary_key = "equipmentid"
  belongs_to :equipment_template , foreign_key: "unittypeid"
  belongs_to :equipment_set , foreign_key: "complectid"
  belongs_to :equipment, foreign_key: "equipmentid"

  def self.new_unit(equipmentid, complectnum, template_equipment_id)
    @equipment_unit = EquipmentUnit.new
    @equipment_unit.equipmentid = equipmentid
    @equipment_unit.complectid =  complectnum
    @equipment_unit.unittypeid = template_equipment_id
    @equipment_unit.save
  end
end

app/controllers/equipment_units_controller.rb
class EquipmentUnitsController < ApplicationController
  before_action :set_equipment_unit, only: [:show, :edit, :update, :destroy]

  # GET /equipment_units
  def index
    @equipment_units = EquipmentUnit.all
  end

  # GET /equipment_units/1
  def show
  end

  # GET /equipment_units/new
  def new
    @equipment_unit = EquipmentUnit.new
    @equipment_templates=EquipmentTemplate.where(va_code_int: params[:set_template_id])
  end

  # GET /equipment_units/1/edit
  def edit
  end
  # POST /equipment_units
  def create
    self.new_eqipment
    #@equipment_unit = EquipmentUnit.new(equipment_unit_params)

    if @equipment_unit.save
      redirect_to @equipment_unit, notice: 'Equipment unit was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /equipment_units/1
  def update
    if @equipment_unit.update(equipment_unit_params)
      redirect_to @equipment_unit, notice: 'Equipment unit was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /equipment_units/1
  def destroy
    @equipment_unit.destroy
    redirect_to equipment_units_url, notice: 'Equipment unit was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipment_unit
      @equipment_unit = EquipmentUnit.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def equipment_unit_params
      params.require(:equipment_unit).permit(:complectid,:unittypeid)
      #params[:equipment_unit]
      #params.require(:@est).permit(all)


      @est
    end
end

app/views/equipment_units/_form.html.erb
<%= form_for(@equipment_unit) do |f| %>
    <table class="list">
      <tbody>
      <% @est=[],[]; a=0 %>
      <% @equipment_templates.each do |et| %>
          <td><%= et.name %></td>
          <td>Введите серийный номер оборудования:</td>
          <td><input type="text" name= a ></td></tr>
          <% @est[a]=et.name, et.contentid; a=a+1 %>
      <% end %>
      </tbody>
    </table>
    <%= f.submit "Сохранить"%>
<% end %>

app/views/equipment_units/edit.html.erb
<h1>Editing Equipment Unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @equipment_unit %> |
<%= link_to 'Back', equipment_units_path %>

app/views/equipment_units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список оборудования входящих в комплекты</h1>

<table>
  <thead>
  <tbody>
    <% @equipment_units.each do |equipment_unit| %>
      <tr>
        <td><%#= equipment_unit.equipment.stationname %></td>
        <td><%= link_to 'Показать', equipment_unit %></td>
        <td><%= link_to 'Редактировать', edit_equipment_unit_path(equipment_unit) %></td>
        <td><%= link_to 'Изменить', equipment_unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Equipment unit', new_equipment_unit_path %>

app/views/equipment_units/new.html.erb
<h1>Новое оборудование комплекта</h1>


<%= render 'form' %>
<%= link_to 'Назад', equipment_units_path %>

app/views/equipment_units/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Редактирование', edit_equipment_unit_path(@equipment_unit) %> |
<%= link_to 'К списку оборудования', equipment_units_path %>