config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :equipment_set_templates
resources :equipment_templates
resources :equipment_sets
resources :equipment_units

get 'equipment_set_templates/:id/upload', to: 'equipment_set_templates#show_upload'
post 'equipment_set_templates/:id/upload', to: 'equipment_set_templates#upload'

get 'equipment_set_templates/:id/error_inv_exel', to: 'equipment_set_templates#error_inv_exel'

get 'equipments/:id/edit_set', to: 'equipments#edit_set'

get 'multiply_issue/:id', :to => 'co#multiply'



# Роуты к шаблонам описывать тут

get 'report_co3/:year/:num', to: 'excel#make_co3'

get 'templates/report_co3/:type/:year/:num', to: 'templates#report_co3'
get 'projects/:project/co6/:num', to: 'templates#make_act_co6'

get 'repairs/list_svod', to: 'repairs#list_svod'
 get 'projects/:project/make_formular', to: 'formulars#make_formular'
get 'projects/:project/make_pasport', to: 'pasports#make_pasport'
get 'make_requisition/:id', :to => 'requisitions#make_requisition'
get 'technique_report/:id', :to => 'technique_report#technique_report'

#resources :organizations

resources :issues do
  member do
    get 'repairs/:file', to: 'repairs#make_file'
    get 'cartridges/:file', to: 'templates#make_file_for_cartridges'
    get 'receive_cartridges', to: 'cartridges#receive_to_tank'
  end
end

resources :projects do
  member do
    get 'act_co3/:year/:month', to: 'templates#make_act_co3'
    #get 'projects/act_co3/:project/:mon/:file', to: 'templates#make_act_co3'
  end
  # resources :printers
  resources :cartridges do
    collection do
      get 'new_tanker'
    end
  end

  resources :equipments do
    member do
      get 'select'
      get 'new_repair'
    end
  end
end

#get 'delete_repair/:equipment_request_id'
#get 'equipments/import' , :to => 'equipments#import'



# get 'projects/:project_id/printers' , :to => 'printers#index'
# get 'printers/:project_id/context_menu' , :to => 'printers#context_menu'
#
# post 'printers/:project/cartridge' , :to => 'printers#cartridge'
# get 'printers/import', :to => 'printers#import'
# get 'printers/export', :to => 'printers#export'
# get 'printers/upload', :to => 'printers#upload'

# get  'issues/:id/cartridge_category/:cartridge', :to => 'cartridges#edit'
# post 'issues/:id/cartridge_category/:cartridge', :to => 'cartridges#update'

post 'role_trackers/reload', :to => 'role_trackers#reload'
resources :role_trackers

resources :organizations do
  member do
    get 'add_cartridge'
    get 'remove_cartridge'
    get :context_menu
  end
  collection do
    get 'import'
    get 'synchronize'
  end
end
resources :floors do
  resources :places
  resources :rooms do
    collection do
      get 'quick_new'
      post 'quick_create'
    end
  end
  member do
    get 'plan'
  end

end
resources :places
#get 'organizations/import', :to => 'organizations#import'

resources :cartridge_categories
resources :printer_categories
resources :equipment_category_groups
resources :equipments
get 'equipments/delete_repair/:id/:project_id/:service_request_id' , :to => 'equipments#delete_repair'
get 'equipment/:equipment/link_to_issue/:issue', :to => 'equipments#set_link_to_issue'
#get 'equipment/destroy_link_from_issue/:issue', :to => 'equipments#destroy_link_from_issue'
get 'issues_without_link', :to => 'equipments#issues_without_link'
get 'synchronize', to: 'repairs#synchronize'

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
  include Ekrtf

  def synchronize
    issues = Issue.where(tracker_id: 6).includes([{ equipment_request: :equipment }, :custom_values])
    issues.each do |issue|
      issue.synchronize_from_equipment_params

      # next unless issue.custom_value_for(50).to_s == '1'
      # if issue.equipment_request && issue.equipment_request.equipment && !issue.equipment_request.request_id.nil?
      #
      #   equipment = issue.equipment_request.equipment
      #   # s_request = issue.service_request
      #   # s_request.hotlineregnum = issue.cf_by_name('Номер заявки ЦCТП')
      #   # issue.custom_field_values   = {22 => equipment.invnumber}
      #   # issue.custom_field_values   = {34 => s_request.check1.problemdscrptn2} if s_request.check1
      #   serial = issue.custom_value_for(21).to_s
      #   #if serial.strip!
      #   #  issue.custom_field_values = {21 => serial}
      #   #end
      #   if serial.to_s == ''
      #     if equipment.sernumber.to_s == ''
      #       issue.custom_field_values = {21 => equipment.sernumber}
      #       issue.custom_field_values = {50 => 0}
      #     else
      #       issue.custom_field_values = {50 => 1}
      #     end
      #   elsif serial == 'б/н' &&  equipment.sernumber.to_s == ''
      #     equipment.sernumber = 'б/н'
      #     equipment.save
      #     issue.custom_field_values = {50 => 0}
      #   elsif serial.to_s == equipment.sernumber
      #     issue.custom_field_values = {50 => 0}
      #   else
      #     issue.custom_field_values = {50 => 1}
      #   end
      # else
      #   issue.custom_field_values = {50 => 1}
      # end
      issue.save_custom_field_values
      #issue.service_request.save
      #issue.save
    end
    redirect_to issues_url, notice: 'Синхронизация осуществлена успешно.'
  end

  def make_file
    issue_id = params[:id].to_i
    template = params[:file]

    @issue      = Issue.find_by_id(issue_id)
    @project_id = @issue.project_id
    @sdmt       = @issue.created_on.to_time
    @project    = Project.find_by_id(@project_id)
    @request    = @issue.equipment_request.service_request
    @check      = @request.check2 || @request.check1
    @equipment  = @request.equipment
    if @equipment.warrantyenddate
      warranty = @equipment.is_warranty_text(@request.regdate)
    else
      warranty = ""
    end
    #Статичные переменные
    pr = {}
    common_static_variable_of_project pr, @project

    pr.merge! 'ActNum' => @request.regnum
    pr.merge! 'year' => @request.regyear
    pr.merge! 'ReqDate' => @request.regdate.strftime("%d.%m.%Y") if @request.regdate # Дата Заявки
    pr.merge! 'ActDateCo7' => @check.checkdate.strftime("%d.%m.%Y") if @check.checkdate
    pr.merge! 'DatePoruch' => Order.order_date(@request.regdate).strftime("%d.%m.%Y")

    pr.merge! 'HardType' => @equipment.equipment_category.name
    pr.merge! 'HardName' => @equipment.stationname
    pr.merge! 'NumInv' => @equipment.invnumber # Инвентарный
    pr.merge! 'NumSer' => @equipment.sernumber # Серийный №
    pr.merge! 'YearBirth' => @equipment.getdate.year.to_s if @equipment.getdate # Год регистрации
    pr.merge! 'warranty' => warranty # cf_by_name("Гарантийный срок")

    pr.merge! 'EndStatus' => @issue.status_write_off? || @issue.status_suspend? ? 'неисправном' : 'исправном'
    pr.merge! 'ActDateCo8' => format_date(@issue.due_date)

    if @request.executant
      pr.merge! 'ActDateCo41' => format_date(@request.executant.senddate)
      pr.merge! 'ActDateCo42' => format_date(@request.executant.sendto_oadt)
      pr.merge! 'Garant' => @request.executant.iswarrantyrepair == 1 ? "Гарантийный" : "Негарантийный"
      pr.merge! 'repairdescription' =>
                    @issue.status_write_off? ? @check.conclusion_name :
                        @issue.status_suspend? ? "ремонтные работы не производились" :
                            @request.executant.repairdescription
      pr.merge! 'work7' =>
                    @issue.status_suspend? ? "Настройки и информация не восстанавливались" :
                        "Произведены восстановление настроек и информации, ПТС введено(ы) в действие."
    end

    if @check
      pr.merge! 'DefOut' => @check.extdamage # Внешние повреждения
      pr.merge! 'DefSeal' => @check.stopperdamage_text
      pr.merge! 'DefSpec' => @check.problemdscrptn # cf_by_name("Проявление неисправности")
      pr.merge! 'DefType' => @check.problemdscrptn2 #cf_by_name("Установленные неисправности")
      pr.merge! 'DefProp' => @check.failure_cause_name #cf_by_name("Установленные причины")
      pr.merge! 'ChapUse' => 'невозможно' #@request.cf_by_name("Использование запчастей")
      pr.merge! 'Komplektnost' => @check.completeness
      pr.merge! 'Usloviya' => @check.operatingconditions_text # cf_by_name("Условия эксплуатации")
      pr.merge! 'ResultDiagnostiki' => @check.conclusion_name # cf_by_name("Заключение")
    end

    generate_rtf_by_template pr, "repair_#{template}.rtf", "repair_#{template}-#{issue_id}.rtf"
  end

  def list_svod
    @service_requests = ServiceRequest.all
  end
end

app/views/issues/repair/_edit.html.haml
- if @issue.equipment_request # Связь с оборудованием установлена
  - sr = @issue.equipment_request.service_request
  = form.fields_for sr do |sr_form|

    -if @issue.can_repair_start_edit? && @issue.status_start? || !sr.check2 && @issue.status_write_off? && @issue.user_can_repair_exec_edit?
      = render 'repairs/check1_edit', sr: sr, form: sr_form
    - else
      = render 'repairs/check1_show', check1: sr.check1
      - if sr.check2
        - if @issue.status_write_off? && @issue.user_can_repair_exec_edit?
          = render 'repairs/check2_edit', sr: sr, form: sr_form
        -else
          = render 'repairs/check2_show', check2: sr.check2
    - if !@issue.status_start?
      - if @issue.user_can_repair_exec_edit?
        = render 'repairs/exec_edit',   sr: sr, form: sr_form
      -else
        = render 'repairs/exec_show',   exec: sr.executant

app/views/issues/repair/_show.html.haml
- if @issue.equipment_request # Связь с оборудованием установлена
  - sr = @issue.equipment_request.service_request
  -# Зачем я это написал?
  -# Аааа, устанавливаем новые связи, для старых задач для которых они не были созданы
  - unless sr.check1
    - sr.check1_id = Check.find_by_requestid(sr.id).id
    -# Находим Исполнение Поскольку Исполнения может и не быть
    - sr.executant_id = Executant.find_by_eqpmntcheckid(sr.check1_id).id
    - sr.save
  = render partial: 'repairs/show_reg_info.html', locals: {sr: sr}
  %br/
  = render partial: 'equipments/info' ,    locals: {equipment: @issue.equipment_request.equipment}
  %br/
  = render partial: 'repairs/check1_show', locals: {check1: sr.check1}
  %br/
  - if sr.check2 && @issue.status_write_off?
    = render partial: 'repairs/check2_show', locals: {check2: sr.check2}
    %br/
  - if !@issue.status_start?
    = render partial: 'repairs/exec_show',   locals: {exec: sr.executant}
    %br
- elsif @issue.equipments_by_inventory # Длина инвномера >3
  - if @issue.equipments_by_inventory.count == 0
    Оборудование по указанному инвентарному номеру не нейдено
  - elsif @issue.equipments_by_inventory.count > 20 # Длина инвномера >3
    Найдено
    - @issue.equipments_by_inventory.count
    единиц оборудования
  - else #Найдено менее 20 единиц оборудования
    %h3 Оборудование найденное по инвентарному номеру:
    %hr/
    - @issue.equipments_by_inventory.each do |equipment|
      %table
        %tr
          %td
            %b= equipment.invnumber
          %td= equipment.sernumber
          %td= equipment.getdate.strftime("%d.%m.%Y") if equipment.getdate
          %td
            - if @issue.user_can_repair_exec_edit?
              =link_to 'Связать', "/equipment/#{equipment.id}/link_to_issue/#{@issue.id}", title: "Будет создана заявка и установлена связь с оборудованием"
            -else
              Для установления связи с оборудованием обратитесь к администратору базы CIA
        %tr
          %td{:colspan => "2"}= equipment.equipment_category.name
          %td{:colspan => "2"}= equipment.status.name if equipment.status
        %tr
          %td{:colspan => "4"}
            %h4= equipment.stationname
- else # Найдено хотябы одно оборудование по инвентарному номеру
  Длина Инвентарного номера не превышает 3х символов
%fieldset
  %legend Документы
  - unless @issue.status.name == 'Новая'
    = button_to "Заявка", "#{issue_path(@issue)}/repairs/request.rtf", class: 'button', method: 'get'
    = button_to "Диагностический акт",   "#{issue_path(@issue)}/repairs/co7.rtf"    , class: 'button', method: 'get'
    = button_to "Акт приема-передачи в ремонт", "#{issue_path(@issue)}/repairs/co41.rtf"   , class: 'button', method: 'get'
    - if @issue.status_repaired? || @issue.status_write_off? || @issue.status_suspend?
      = button_to "Акт приема-передачи из ремонта", "#{issue_path(@issue)}/repairs/co42.rtf"   , class: 'button', method: 'get'
    - if @issue.status_repaired?
      = button_to "Акт ввода в эксплуатацию",   "#{issue_path(@issue)}/repairs/co8.rtf"    , class: 'button', method: 'get'
  - else
    Для формирования актов задачу необходимо перевести в состоние "Сформирована"

app/views/issues/repair/_show_old.erb
<hr>

<%#
   param = ['Номер производства','Дата акта СО7','Тип оборудования','Наименование оборудования','Наименование оборудования',
            'Год выпуска','Внешние повреждения','Пломбы','Проявление неисправности','Установленные неисправности',
            'Установленные причины','Зав. №','Использование запчастей','Гарантийный срок',
            'Комплектность ПТС','Условия эксплуатации','Заключение']
   errors = []

   param.each do |item|
     if @issue.custom_value_for(CustomField.find_by_name(item)).to_s == ''
       errors << item
     end
   end
%>

<div>
  <% if not @issue.equipment_request.nil? # Связь с оборудованием установлена%>
    <%= render partial: 'equipments/info' ,   locals: {equipment: @issue.equipment_request.equipment} %>
    <br>
    <%= render partial: 'repairs/check1_show', locals: {rc: @issue.equipment_request.service_request} %>
  <% elsif @issue.equipments_by_inventory # Длина инвномера >3%>
      <% if @issue.equipments_by_inventory.count == 0 %>
        Оборудование по указанному инвентарному номеру не нейдено
      <% elsif @issue.equipments_by_inventory.count > 20 # Длина инвномера >3%>
        Найдено <% @issue.equipments_by_inventory.count %> единиц оборудования
      <% else #Найдено менее 20 единиц оборудования%>
        <h3>Оборудование найденное по инвентарному номеру:</h3>
        <hr>
        <% @issue.equipments_by_inventory.each do |equipment| %>
          <table>
            <tr>
              <td><b><%= equipment.invnumber %></b></td>
              <td><%= equipment.sernumber %></td>
              <td><%= equipment.getdate.strftime("%d.%m.%Y") if equipment.getdate %></td>
              <td><%= link_to 'Связать', "/equipment/#{equipment.id}/link_to_issue/#{@issue.id}", title: "Будет создана заявка и установлена связь с оборудованием" %></td>
            </tr>
            <tr>
              <td colspan="2"><%= equipment.equipmenttype.name %></td>
              <td colspan="2"><%= equipment.status.name if equipment.status %></td>
            </tr>
            <tr><td colspan="4"><h4><%= equipment.stationname %></h4></td></tr>
          </table>
          <hr>
        <% end %>
      <% end %>
  <% else # Найдено хотябы одно оборудование по инвентарному номеру%>
    Длина Инвентарного номера не превышает 3х символов
  <% end %>
</div>

<div name="co7error" style="background-color:#8aaeff">Формирование актов СО-7 и СО-4.1
  <%if 1==1 #  errors.size==0%>
    <%= button_to "Заявка", "#{issue_path(@issue)}/repairs/zayavka.rtf", class: 'button', method: 'get' %>
    <%= button_to "CO-7",   "#{issue_path(@issue)}/repairs/co7.rtf"    , class: 'button', method: 'get' %>
    <%= button_to "CO-4.1", "#{issue_path(@issue)}/repairs/co41.rtf"   , class: 'button', method: 'get' %>
    <%= button_to "CO-4.2", "#{issue_path(@issue)}/repairs/co42.rtf"   , class: 'button', method: 'get' %>
  <% else %>
    <div style="background-color:#5199ff;color:#6a0000;"> <b>заполните обязательные поля в задаче</b></div>
    <% errors.each { |error_item| %>
      <div style="background-color:#5199ff;color:#ff0000;"> <%= error_item %></div>
    <% } %>
  <% end %>
</div>



<script language="javascript">
    function openPopupWin()
    {
        var sDesrc;
        var sParams = new Array(6);

// настройки открываемого окна браузера
        sParams[0] = "500"; // ширина окна в пикселях
        sParams[1] = "250"; // высота окна в пикселях
// "no" - скрыть элемент, "yes" - показать
        sParams[2] = "no"; // наличие статус строки
        sParams[3] = "no"; // наличие кнопок (toolbar)
        sParams[4] = "no"; // наличие меню
        sParams[5] = "no"; // наличие скроллингов
        sDesrc = "width=" + sParams[0] + ", height=" + sParams[1] +
                ", status=" + sParams[2] + ", toolbar=" + sParams[3] +
                ", menubar=" + sParams[4] + ", scrollbars=" + sParams[5];
        var win = window.open("", "СО-4.2 : Введите дополнительные данные", sDesrc);
        win.document.open();
        win.document.writeln("Функционал генератора на доработке");
    }
</script>