config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :equipment_set_templates
resources :equipment_templates
resources :equipment_sets
resources :equipment_units

get 'equipment_set_templates/:id/upload', to: 'equipment_set_templates#show_upload'
post 'equipment_set_templates/:id/upload', to: 'equipment_set_templates#upload'

get 'equipment_set_templates/:id/error_inv_exel', to: 'equipment_set_templates#error_inv_exel'

get 'equipments/:id/edit_set', to: 'equipments#edit_set'

get 'multiply_issue/:id', :to => 'co#multiply'



# Роуты к шаблонам описывать тут

get 'report_co3/:year/:num', to: 'excel#make_co3'

get 'templates/report_co3/:type/:year/:num', to: 'templates#report_co3'
get 'projects/:project/co6/:num', to: 'templates#make_act_co6'

get 'repairs/list_svod', to: 'repairs#list_svod'
 get 'projects/:project/make_formular', to: 'formulars#make_formular'
get 'projects/:project/make_pasport', to: 'pasports#make_pasport'
get 'make_requisition/:id', :to => 'requisitions#make_requisition'
get 'technique_report/:id', :to => 'technique_report#technique_report'

#resources :organizations

resources :issues do
  member do
    get 'repairs/:file', to: 'repairs#make_file'
    get 'cartridges/:file', to: 'templates#make_file_for_cartridges'
    get 'receive_cartridges', to: 'cartridges#receive_to_tank'
  end
end

resources :projects do
  member do
    get 'act_co3/:year/:month', to: 'templates#make_act_co3'
    #get 'projects/act_co3/:project/:mon/:file', to: 'templates#make_act_co3'
  end
  # resources :printers
  resources :cartridges do
    collection do
      get 'new_tanker'
    end
  end

  resources :equipments do
    member do
      get 'select'
      get 'new_repair'
    end
  end
end

#get 'delete_repair/:equipment_request_id'
#get 'equipments/import' , :to => 'equipments#import'



# get 'projects/:project_id/printers' , :to => 'printers#index'
# get 'printers/:project_id/context_menu' , :to => 'printers#context_menu'
#
# post 'printers/:project/cartridge' , :to => 'printers#cartridge'
# get 'printers/import', :to => 'printers#import'
# get 'printers/export', :to => 'printers#export'
# get 'printers/upload', :to => 'printers#upload'

# get  'issues/:id/cartridge_category/:cartridge', :to => 'cartridges#edit'
# post 'issues/:id/cartridge_category/:cartridge', :to => 'cartridges#update'

post 'role_trackers/reload', :to => 'role_trackers#reload'
resources :role_trackers

resources :organizations do
  member do
    get 'add_cartridge'
    get 'remove_cartridge'
    get :context_menu
  end
  collection do
    get 'import'
    get 'synchronize'
  end
end
resources :floors do
  resources :places
  resources :rooms do
    collection do
      get 'quick_new'
      post 'quick_create'
    end
  end
  member do
    get 'plan'
  end

end
resources :places
#get 'organizations/import', :to => 'organizations#import'

resources :cartridge_categories
resources :printer_categories
resources :equipment_category_groups
resources :equipments
get 'equipments/delete_repair/:id/:project_id/:service_request_id' , :to => 'equipments#delete_repair'
get 'equipment/:equipment/link_to_issue/:issue', :to => 'equipments#set_link_to_issue'
#get 'equipment/destroy_link_from_issue/:issue', :to => 'equipments#destroy_link_from_issue'
get 'issues_without_link', :to => 'equipments#issues_without_link'
get 'synchronize', to: 'repairs#synchronize'

app/views/project/_list_of_so.html.haml
- if @project.name == 'Техподдержка'|| @project.name == 'ФГБУ'
- else
  =form_tag( project_path(@project) + "/make_formular/", :method => :get) do
    = date_field_tag 'from', :from
    = date_field_tag 'to', :to
    = submit_tag "Сформировать формуляр"
  %p
    = link_to 'Паспорт ТС',  project_path(@project)+'/make_pasport'
- current_year = Time.now.year
- (2015..current_year).each do |year|
  - last_month = year==current_year ? Time.now.month.to_i : 12
  %p
    %b= "Документация за #{year}й год:"
  - if @project.name == 'Техподдержка'
    %p
      = "Квартальные отчеты CO-3 в формате xlsx с наростающим:"
      = (1..4).collect{|num| link_to num, controller: :excel,  action: :make_co3, year: year, num: num}.join(', ').html_safe
    %p
  - else
    %p
      = "Акты СО-3 за #{year}й год:"
      - (1..last_month).each do |month|
        = link_to month, project_path(@project) + "/act_co3/#{year}/#{month}" #, remote: true
        = ', ' unless month == last_month
    %p
      Шаблоны Актов СО-6:
      - if year==2015
        = link_to '28', project_path(@project)+'/co6/28'
        = ', '
        = link_to '29',  project_path(@project)+'/co6/29'
      - if year==2016
        = link_to '30',  project_path(@project)+'/co6/30'
        = ', '
        = link_to '31',  project_path(@project)+'/co6/31'
      - if year==2017
        = link_to '32',  project_path(@project)+'/co6/32'
        = ', '
        = link_to '33',  project_path(@project)+'/co6/33'
      - if year==2018
        = link_to '34',  project_path(@project)+'/co6/34'
        = ', '
        = link_to '35',  project_path(@project)+'/co6/35'
      - if year==2019
        - if @project.oa_code.include?('GV')
          = link_to '36-gvs',  project_path(@project)+'/co6/36-gvs'
        - else
          = link_to '36',  project_path(@project)+'/co6/36'
        %p
          = link_to 'Присяжные',  project_path(@project)+'/co6/p'