config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :equipment_set_templates
resources :equipment_templates
resources :equipment_sets
resources :equipment_units

get 'equipment_set_templates/:id/upload', to: 'equipment_set_templates#show_upload'
post 'equipment_set_templates/:id/upload', to: 'equipment_set_templates#upload'

get 'equipment_set_templates/:id/error_inv_exel', to: 'equipment_set_templates#error_inv_exel'

get 'equipments/:id/edit_set', to: 'equipments#edit_set'

get 'multiply_issue/:id', :to => 'co#multiply'



# Роуты к шаблонам описывать тут

get 'report_co3/:year/:num', to: 'excel#make_co3'

get 'templates/report_co3/:type/:year/:num', to: 'templates#report_co3'
get 'projects/:project/co6/:num', to: 'templates#make_act_co6'

get 'repairs/list_svod', to: 'repairs#list_svod'
 get 'projects/:project/make_formular', to: 'formulars#make_formular'
get 'projects/:project/make_pasport', to: 'pasports#make_pasport'
get 'make_requisition/:id', :to => 'requisitions#make_requisition'
get 'technique_report/:id', :to => 'technique_report#technique_report'

#resources :organizations

resources :issues do
  member do
    get 'repairs/:file', to: 'repairs#make_file'
    get 'cartridges/:file', to: 'templates#make_file_for_cartridges'
    get 'receive_cartridges', to: 'cartridges#receive_to_tank'
  end
end

resources :projects do
  member do
    get 'act_co3/:year/:month', to: 'templates#make_act_co3'
    #get 'projects/act_co3/:project/:mon/:file', to: 'templates#make_act_co3'
  end
  # resources :printers
  resources :cartridges do
    collection do
      get 'new_tanker'
    end
  end

  resources :equipments do
    member do
      get 'select'
      get 'new_repair'
    end
  end
end

#get 'delete_repair/:equipment_request_id'
#get 'equipments/import' , :to => 'equipments#import'



# get 'projects/:project_id/printers' , :to => 'printers#index'
# get 'printers/:project_id/context_menu' , :to => 'printers#context_menu'
#
# post 'printers/:project/cartridge' , :to => 'printers#cartridge'
# get 'printers/import', :to => 'printers#import'
# get 'printers/export', :to => 'printers#export'
# get 'printers/upload', :to => 'printers#upload'

# get  'issues/:id/cartridge_category/:cartridge', :to => 'cartridges#edit'
# post 'issues/:id/cartridge_category/:cartridge', :to => 'cartridges#update'

post 'role_trackers/reload', :to => 'role_trackers#reload'
resources :role_trackers

resources :organizations do
  member do
    get 'add_cartridge'
    get 'remove_cartridge'
    get :context_menu
  end
  collection do
    get 'import'
    get 'synchronize'
  end
end
resources :floors do
  resources :places
  resources :rooms do
    collection do
      get 'quick_new'
      post 'quick_create'
    end
  end
  member do
    get 'plan'
  end

end
resources :places
#get 'organizations/import', :to => 'organizations#import'

resources :cartridge_categories
resources :printer_categories
resources :equipment_category_groups
resources :equipments
get 'equipments/delete_repair/:id/:project_id/:service_request_id' , :to => 'equipments#delete_repair'
get 'equipment/:equipment/link_to_issue/:issue', :to => 'equipments#set_link_to_issue'
#get 'equipment/destroy_link_from_issue/:issue', :to => 'equipments#destroy_link_from_issue'
get 'issues_without_link', :to => 'equipments#issues_without_link'
get 'synchronize', to: 'repairs#synchronize'

app/models/room.rb
# t.integer :floor_id
# t.string :name
# t.integer :category
# t.string :area
# t.integer :ord
class Room < ActiveRecord::Base
  unloadable
  include Redmine::SafeAttributes
  belongs_to :floor
  has_many :places

  safe_attributes :name, :area, :category, :move_to

  attr_protected :id

  serialize :point, Hash
  acts_as_list column: :ord, scope: :floor

  scope :ordered, ->{order(:ord)}

  CATEGORIES = {1=>:cabinets,
                2=>:courtrooms,
                3=>:halls,
                4=>:backrooms,
                100=>:another}

  def self.categories
    CATEGORIES
  end

  def self.categories_for_select
    CATEGORIES.map do |h|
      [Room.rus_name(h.first), h.first]
    end
  end

  def self.short_rus_name category
    case category
      when 1 then 'Каб.'
      when 2 then 'Зал'
      when 3 then 'Холл'
      when 4 then 'Сл.'
      when 100 then 'Пом.'
    end
  end

  def self.rus_name category
    case category
      when 1 then 'Кабинет'
      when 2 then 'Зал судебных заседаний'
      when 3 then 'Холл'
      when 4 then 'Служебное помещение'
      when 100 then 'Помещение'
    end
  end

  def category_tname
    Room.rus_name (self.category)
  end

  def work_places
    self.places.where(category: 1).count
  end

  def other_places
    self.places.where('category <> 1').count
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  unloadable
  before_filter :set_floor
  before_filter :set_room, only: [:show, :edit, :update, :destroy]

  def index
    @rooms = @floor.rooms.ordered
    redirect_to quick_new_floor_rooms_path(@floor) if @rooms.size==0
  end

  def show
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new
    @room.floor = @floor
    if @room.update_attributes(params[:room])
      @json ? render_json_room : redirect_to(floor_rooms_path(@floor), notice: 'Помещение изменено.')
    else
      @json ? render_json_room_error : render(:edit)
    end
  end

  def edit
  end

  def update
    #@place.safe_attributes = params[:place]
    if @room.update_attributes(params[:room])
      @json ? render_json_room : redirect_to(floor_rooms_path(@floor), notice: 'Помещение изменено.')
    else
      @json ? render_json_room_error : render(:edit)
    end
  end

  def destroy
    @room.destroy
    if @json
      render(json: {status: :ok}, status: :ok, location: @room)
    else
      redirect_to(floor_rooms_path(@floor), notice: 'Помещение удалено.')
    end
  end

  def quick_new
  end

  def quick_create
    rooms = params[:floor]
    rooms.each do |category, room|
      id = room[:id].to_i
      name = Room.short_rus_name(id)
      count = room[:count].to_i
      range = room[:range].gsub(/ *\- */, '-').split(' ')
      nums = []
      last_num = nil
      range.each do |num|
        case num
          when /^[0-9]+$/
            nums << num.to_i
          when /^[0-9]+\-[0-9]+$/
            nums += Range.new(*num.split('-').map(&:to_i)).to_a
          when /^[0-9]+\-$/
            last_num = num.sub('-', '').to_i
        end
      end
      last_num ||= nums.last
      if (dif = count - nums.count) > 0
        nums += Range.new(last_num, last_num+dif-1).to_a
      else
        nums = nums[0...count]
      end
      nums.each do |num|
        room = Room.new
        room.floor_id = @floor.id
        room.category = id
        room.name = "#{name} №#{num}"
        room.save
      end
    end
    redirect_to(floor_rooms_path(@floor), notice: 'Помещение удалено.')
  end

  private

  def set_floor
    @floor = Floor.find(params[:floor_id])
    @building = @floor.building
    @organization = @building.organization
    @json =  params[:ajax]&&params[:ajax]=='json'
  end

  def set_room
    @room = Room.find(params[:id])
  end

  def render_json_room
    place = {room:
                 {id: @room.id,
                  name: @room.name,
                  category: @room.category,
                  area: @room.area}
    }
    render(json: room, status: :ok, location: @room)
  end

  def render_json_place_error
    render( json: @place.errors, status: :unprocessable_entity)
  end

end

app/views/rooms/_form.haml
= labelled_form_for [@floor, @room], multipart: true do |f|
  = error_messages_for @room
  .box.tabular
    %p= f.text_field :name, :required => true, :size => 60
    %p= f.select :category, Room.categories_for_select, required: true
    %p= f.text_field :area, :size => 60
  = f.submit

app/views/rooms/edit.haml
= title [@organization.name, organization_path(@organization)],
  [@building.name, floors_path(building: @building)],
  [@floor.name, floor_rooms_path(@floor)],
  @room.name
=render 'form'

app/views/rooms/index.haml
.contextual
  = link_to 'Новое помещение', new_floor_room_path(@floor), :class => 'icon icon-add'
  -#|
  -#= link_to 'Редактировать помещение', edit_floor_room_path(@floor, @room) if @room
= title [@organization.name, organization_path(@organization)],
  [@building.name, floors_path(building: @building)],
  [@floor.name, floors_path(building: @building, selected: @floor)],
  'Список помещений'
.splitcontentleft#list-left
  .mypage-box
    %table.list
      %thead
        %tr
          %th Наименование
          %th Тип
          %th Полигон
          %th Рабочих мест
          %th Иных точек
          %th=l(:button_sort)
          %th
      %tbody
        - @rooms.each do |room|
          %tr{:class => "hascontextmenu #{cycle('odd', 'even')}"}
            %td= room.name
            %td= room.category_tname
            %td= room.area
            %td= room.work_places
            %td= room.other_places
            %td.reorder= reorder_links 'room', {:action => 'update', floor_id: @floor.id, :id => room.id}, :put #{:action => 'update', floor_id: @floor.id, :id => place.id}, :put floor_place_path(@floor,place)
            %td.buttons
              = link_to l(:button_edit), edit_floor_room_path(@floor, room), :class => 'icon icon-edit'
              = delete_link floor_room_path(@floor, room)

app/views/rooms/new.haml
= title [@organization.name, organization_path(@organization)],
  [@building.name, floors_path(building: @building)],
  [@floor.name, floor_rooms_path(@floor)],
  "Новое помещение"
=render 'form'

app/views/rooms/quick_new.haml
= title [@organization.name, organization_path(@organization)],
  [@building.name, floors_path(building: @building)],
  'Быстрая регистрация помещений'
= form_for @floor, url: { controller: 'rooms', :action => "quick_create" }, method: :post do |f|
  .box.tabular
    - Room::CATEGORIES.each do |id, name|
      %p
        = label "floor[#{name}]", name
        = hidden_field "floor[#{name}]", :id, value: id
        = text_field "floor[#{name}]", :count, value: 0, in: 0...100, step: 1, :required => true, :size => 20
        диапазон номеров (1-5 8 10):
        = text_field "floor[#{name}]", :range, value: '1-', :required => true, :size => 20
  = f.submit "Создать"